---
title: "All Users Library 3L Reference Controls"
---

```{r}
#| code-fold: true
#| warning: false
#| message: false
library(purrr)
library(dplyr)
library(Luciernaga)
library(htmltools)
```

```{r}
#| code-fold: true
path <- file.path("G:", "3L_Library")
files <- list.files(path, full.names = TRUE)
LibraryControls <- map(.x=files, .f=QC_LibraryParse, returntype="data")

LibraryControls <- LibraryControls[sapply(LibraryControls, ncol) == 42]

Data <- bind_rows(LibraryControls)
FluorophoreList <- Data %>% pull(Fluorophore) %>% unique()

FluorophoreList <- FluorophoreList[!grepl("Negative", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("stained", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("STAINED", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("omato", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("eads", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("ito", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("nstain", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("egative", FluorophoreList)]
FluorophoreList <- FluorophoreList[!grepl("UNSTAIN", FluorophoreList)]

Plots <- map(.x=FluorophoreList, .f=Luciernaga:::LibraryPlotWrapper, data=Data, myfactor="DateTime", animate=TRUE)

l <- htmltools::tagList()
for(i in seq_along(Plots)) {
  l[[i]] <- tagList(Plots[[i]])
}
```

```{r}
#| code-fold: true
l
```
